repos:
- repo: https://github.com/pre-commit/mirrors-prettier
  rev: "cafd550" # Use the sha or tag you want to point at
  hooks:
    - id: prettier
      additional_dependencies:
        - prettier-plugin-svelte
