name: "release-build-windows"
on:
  push:
    tags:
      - "*.*.*"

jobs:
  build:
    strategy:
      fail-fast: false
    
    runs-on: windows-2022
    steps:
      - uses: actions/checkout@v3
      - name: Set env
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $env:GITHUB_ENV
      - name: Set Tauri Signature env
        run: echo ${{ secrets.TAURI_PRIVATE_KEY }} >> $env:GITHUB_ENV && echo ${{ secrets.TAURI_KEY_PASSWORD }} >> $env:GITHUB_ENV
      - name: setup node
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: install Rust stable
        uses: dtolnay/rust-toolchain@stable
      - name: build
        run: npm install && npm run deploy
      - name: Attach files to release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            beiboot-desktop_${{ RELEASE_VERSION }}_x64_en-US.msi
            beiboot-desktop_${{ RELEASE_VERSION }}_x64_en-US.msi.zip
            beiboot-desktop_${{ RELEASE_VERSION }}_x64_en-US.msi.zip.sig
