name: "release-build-windows"
on:
  push:
    tags:
      - "*.*.*"

jobs:
  build:
    strategy:
      fail-fast: false
    
    runs-on: windows-2022
    steps:
      - uses: actions/checkout@v3
      - name: Set Tauri Signature Private Key
        run: echo ${{ secrets.TAURI_PRIVATE_KEY }} | Out-File -FilePath $env:GITHUB_ENV 
      - name: Set Tauri Sig Password
        run: echo ${{ secrets.TAURI_KEY_PASSWORD }} | Out-File -FilePath $env:GITHUB_ENV 
      - name: setup node
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: install Rust stable
        uses: dtolnay/rust-toolchain@stable
      - name: build
        run: npm install && npm run deploy
      - name: Attach files to release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            getdeck-desktop_${{ github.ref_name }}_x64_en-US.msi
            getdeck-desktop_${{ github.ref_name }}_x64_en-US.msi.zip
            getdeck-desktop_${{ github.ref_name }}_x64_en-US.msi.zip.sig
