name: "release-build-macos"
on:
  push:
    tags:
      - "*.*.*"

jobs:
  build:
    strategy:
      fail-fast: false
    
    runs-on: macos-latest 
    steps:
      - uses: actions/checkout@v3
      - name: Set Tauri signature private key 
        run: echo "TAURI_PRIVATE_KEY=${{ secrets.TAURI_PRIVATE_KEY }}" >> $GITHUB_ENV
      - name: Set Tauri signature private key password
        run: echo "TAURI_KEY_PASSWORD=${{ secrets.TAURI_KEY_PASSWORD }}" >> $GITHUB_ENV
      - name: setup node
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: install Rust stable
        uses: dtolnay/rust-toolchain@stable
      - name: build
        run: npm install && npm run deploy
      - name: Attach files to release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            src-tauri/target/release/bundle/dmg/Getdeck-Desktop_${{ github.ref_name }}_aarch64.dmg 
            src-tauri/target/release/bundle/macos/Getdeck-Desktop.app
            src-tauri/target/release/bundle/macos/Getdeck-Desktop.app.tar.gz
            src-tauri/target/release/bundle/macos/Getdeck-Desktop.app.tar.gz.sig


